# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservices/storage_service/proto/storage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'microservices/storage_service/proto/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1microservices/storage_service/proto/storage.proto\" \n\x0b\x44\x61taRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"\x1c\n\x0c\x44\x61taResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t2D\n\x0eStorageService\x12\x32\n\x11GetHistoricalData\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservices.storage_service.proto.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=53
  _globals['_DATAREQUEST']._serialized_end=85
  _globals['_DATARESPONSE']._serialized_start=87
  _globals['_DATARESPONSE']._serialized_end=115
  _globals['_STORAGESERVICE']._serialized_start=117
  _globals['_STORAGESERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
